plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "storage/**/*"
    - "node_modules/**/*"

# rspec:install で生成される rails_helper.rb のテンプレ抜粋
Rails/Exit:
  Exclude:
    - "spec/rails_helper.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "config/environments/*.rb"

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5
